server:
  port: 8412

spring:
  datasource:
    dynamic:
      primary: ems-biz
      strict: false
      datasource:
        ems-biz:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://183.56.196.43:3306/ems_biz?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: test
          password: obK_Zc@3Epf8p
        jetlinks-ts:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:TAOS-RS://183.56.196.43:6041/jetlinks?user=root&password=taosdata
          username: root
          password: taosdata

mybatis-plus:
  - classpath:com/gsta/ems/mock/dao/*/*Mapper.xml

